# Generated by Django 4.0.4 on 2022-04-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
