# Generated by Django 4.0.4 on 2022-04-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedinapp', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='linkedinapp.profile'),
        ),
    ]
